#cloud-config

coreos:
  units:
    - name: update-engine.service
      mask: true
    - name: locksmithd.service
      mask: true
    - name: scripts.service
      command: start
      content: |
        [Unit]
        Description=Configuration scripts
        Requires=network-online.target docker.service
        After=docker.service git-daemon.service

        [Service]
        EnvironmentFile=/etc/farm-environment
        RemainAfterExit=yes
        ExecStartPre=/usr/bin/rm -rf /tmp/tf-module
        ExecStartPre=-/usr/bin/docker rm -f %p
        ExecStartPre=-/usr/bin/docker pull quay.io/swi-infra/git-autoupdate
        ExecStartPre=/usr/bin/git clone --depth 1 $${CONFIG_URL} /tmp/tf-module
        ExecStart=/usr/bin/docker run \
                                      --name %p \
                                      -e GIT_URL=$${CONFIG_URL} \
                                      -e VOLUME_PATH=/tf-module \
                                      -v /tmp/tf-module:/tf-module \
                                      quay.io/swi-infra/git-autoupdate
        ExecStop=/usr/bin/docker kill %p
        Restart=always
        RestartSec=10s
        TimeoutStartSec=0
        TimeoutStopSec=15
    - name: data-storage.service
      command: start
      content: |
        [Unit]
        Description=Local storage
        Requires=scripts.service
        After=scripts.service

        [Service]
        EnvironmentFile=/etc/farm-environment
        Type=oneshot
        RemainAfterExit=yes
        ExecStart=/tmp/tf-module/scripts/disk-mgmt start $${MACHINE_TYPE}
        ExecStop=/tmp/tf-module/scripts/disk-mgmt stop $${MACHINE_TYPE}
        TimeoutStartSec=0
    - name: glusterfs.service
      command: start
      content: |
        [Unit]
        Description=Shared storage
        Requires=scripts.service data-storage.service
        After=scripts.service data-storage.service

        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStart=/tmp/tf-module/scripts/glusterfs-mgmt start
        ExecStop=/tmp/tf-module/scripts/glusterfs-mgmt stop
        TimeoutStartSec=0
    - name: postgres.service
      command: start
      content: |
        [Unit]
        Description=PostgreSQL
        After=docker.service data-storage.service
        Requires=docker.service data-storage.service

        [Service]
        ExecStartPre=-/usr/bin/docker rm -f %p
        ExecStartPre=-/usr/bin/docker network create gerrit
        ExecStartPre=/usr/bin/docker pull postgres:11.1-alpine
        ExecStart=/usr/bin/docker run \
                              --name %p \
                              --rm \
                              -p 5432:5432 \
                              --net gerrit \
                              --env-file /storage/services/postgres/gerrit-postgres-environment \
                              --volume /storage/services/postgres/data:/var/lib/postgresql/data \
                              postgres:11.1-alpine
        ExecStop=/usr/bin/docker kill %p
        Restart=always
        RestartSec=10s
        TimeoutStartSec=0
        TimeoutStopSec=15
    - name: gerrit.service
      command: start
      content: |
        [Unit]
        Description=Gerrit
        After=docker.service postgres.service data-storage.service glusterfs.service
        Requires=docker.service postgres.service data-storage.service glusterfs.service

        [Service]
        ExecStart=/tmp/tf-module/scripts/gerrit-mgmt start
        ExecStop=/tmp/tf-module/scripts/gerrit-mgmt stop
        Restart=always
        RestartSec=10s
        TimeoutStartSec=0
        TimeoutStopSec=15
    - name: nginx-proxy.service
      command: start
      content: |
        [Unit]
        Description=Nginx proxy
        After=docker.service data-storage.service glusterfs.service
        Requires=docker.service data-storage.service glusterfs.service

        [Service]
        ExecStart=/tmp/tf-module/scripts/proxy-mgmt start nginx-proxy
        ExecStop=/tmp/tf-module/scripts/proxy-mgmt stop nginx-proxy
        Restart=always
        RestartSec=10s
        TimeoutStartSec=0
        TimeoutStopSec=15
    - name: letsencrypt.service
      command: start
      content: |
        [Unit]
        Description=Let's encrypt (HTTPS)
        After=docker.service data-storage.service glusterfs.service nginx-proxy.service
        Requires=docker.service data-storage.service glusterfs.service nginx-proxy.service

        [Service]
        ExecStart=/tmp/tf-module/scripts/proxy-mgmt start letsencrypt
        ExecStop=/tmp/tf-module/scripts/proxy-mgmt stop letsencrypt
        Restart=always
        RestartSec=10s
        TimeoutStartSec=0
        TimeoutStopSec=15

write_files:
  - path: /etc/waagent.conf
    permissions: 0644
    owner: root
    content: |
      ResourceDisk.Format=y
      ResourceDisk.EnableSwap=y
  - path: /etc/farm-environment
    permissions: 0644
    owner: root
    content: |
      MACHINE_TYPE=gerrit-master
      FARM_PLATFORM=cloud-azure
      CONFIG_URL=${config_url}
      HOST_HOSTNAME=${gerrit_hostname}
      GERRIT_MIRROR_IPS=${gerrit_mirror_ips}
  - path: /etc/gerrit-environment
    permissions: 0644
    owner: root
    content: |
      UI=${gerrit_ui}
      AUTH_TYPE=${gerrit_auth_type}
      TRANSFER_TIMEOUT=20 m
      RECEIVE_TIMEOUT=20 m
      SSHD_IDLETIMEOUT=10 m
      SSHD_WAITTIMEOUT=20 m
      OAUTH_GITHUB_CLIENT_ID=${gerrit_oauth_github_client_id}
      OAUTH_GITHUB_CLIENT_SECRET=${gerrit_oauth_github_client_secret}
      OAUTH_OFFICE365_CLIENT_ID=${gerrit_oauth_office365_client_id}
      OAUTH_OFFICE365_CLIENT_SECRET=${gerrit_oauth_office365_client_secret}
      OAUTH_GOOGLE_CLIENT_ID=${gerrit_oauth_google_client_id}
      OAUTH_GOOGLE_CLIENT_SECRET=${gerrit_oauth_google_client_secret}
      OAUTH_BITBUCKET_CLIENT_ID=${gerrit_oauth_bitbucket_client_id}
      OAUTH_BITBUCKET_CLIENT_SECRET=${gerrit_oauth_bitbucket_client_secret}
      OAUTH_GITLAB_CLIENT_ID=${gerrit_oauth_gitlab_client_id}
      OAUTH_GITLAB_CLIENT_SECRET=${gerrit_oauth_gitlab_client_secret}
      OAUTH_AIRVANTAGE_CLIENT_ID=${gerrit_oauth_airvantage_client_id}
      OAUTH_AIRVANTAGE_CLIENT_SECRET=${gerrit_oauth_airvantage_client_secret}
      DATABASE_TYPE=postgresql
      DATABASE_HOSTNAME=postgres
      DATABASE_PORT=5432
      DATABASE_DATABASE=reviewdb
      DATABASE_USERNAME=gerrit2

